version: "3"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'poll'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3316:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  web:
    build: .
    ports:
      - "5000:5000"
volumes:
  my-db:
